apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

helmCharts:
  - name: backstage
    repo: https://backstage.github.io/charts
    version: 2.6.3
    releaseName: backstage
    namespace: backstage
    valuesFile: values.yaml

resources:
  - namespace.yaml
  - postgres.yaml
  - k8s-rbac.yaml

generatorOptions:
  disableNameSuffixHash: true
