apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://strimzi.io/install/latest?namespace=kafka
  - https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml
  - https://github.com/apache/camel-k/releases/download/v2.5.0/camel-k-operator.yaml

namespace: operators
